//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Web.NewSendMsg {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NewSendMsgSoap", Namespace="http://192.168.1.125:8002/")]
    public partial class NewSendMsg : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsg_315OperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsg_Budiot_XFGWNormalOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsg_Budiot_ET315WNormalOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsg_Budiot_XFBNormalOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsg_Budiot_CXTSNormalOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsg_Budiot_MQYNormalOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsg_xianglehuiOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsg_Budiot_Wisdom315OperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsg_Budiot_Wisdom315NormalOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsg_Budiot_Wisdom315NormalAsmxOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsg_Budiot_XLHOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsg_Budiot_XLHNormalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NewSendMsg() {
            this.Url = global::Web.Properties.Settings.Default.Web_NewSendMsg_NewSendMsg;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendMsgCompletedEventHandler SendMsgCompleted;
        
        /// <remarks/>
        public event SendMsg_315CompletedEventHandler SendMsg_315Completed;
        
        /// <remarks/>
        public event SendMsg_Budiot_XFGWNormalCompletedEventHandler SendMsg_Budiot_XFGWNormalCompleted;
        
        /// <remarks/>
        public event SendMsg_Budiot_ET315WNormalCompletedEventHandler SendMsg_Budiot_ET315WNormalCompleted;
        
        /// <remarks/>
        public event SendMsg_Budiot_XFBNormalCompletedEventHandler SendMsg_Budiot_XFBNormalCompleted;
        
        /// <remarks/>
        public event SendMsg_Budiot_CXTSNormalCompletedEventHandler SendMsg_Budiot_CXTSNormalCompleted;
        
        /// <remarks/>
        public event SendMsg_Budiot_MQYNormalCompletedEventHandler SendMsg_Budiot_MQYNormalCompleted;
        
        /// <remarks/>
        public event SendMsg_xianglehuiCompletedEventHandler SendMsg_xianglehuiCompleted;
        
        /// <remarks/>
        public event SendMsg_Budiot_Wisdom315CompletedEventHandler SendMsg_Budiot_Wisdom315Completed;
        
        /// <remarks/>
        public event SendMsg_Budiot_Wisdom315NormalCompletedEventHandler SendMsg_Budiot_Wisdom315NormalCompleted;
        
        /// <remarks/>
        public event SendMsg_Budiot_Wisdom315NormalAsmxCompletedEventHandler SendMsg_Budiot_Wisdom315NormalAsmxCompleted;
        
        /// <remarks/>
        public event SendMsg_Budiot_XLHCompletedEventHandler SendMsg_Budiot_XLHCompleted;
        
        /// <remarks/>
        public event SendMsg_Budiot_XLHNormalCompletedEventHandler SendMsg_Budiot_XLHNormalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.125:8002/SendMsg", RequestNamespace="http://192.168.1.125:8002/", ResponseNamespace="http://192.168.1.125:8002/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMsg(string tele, string msg) {
            object[] results = this.Invoke("SendMsg", new object[] {
                        tele,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMsgAsync(string tele, string msg) {
            this.SendMsgAsync(tele, msg, null);
        }
        
        /// <remarks/>
        public void SendMsgAsync(string tele, string msg, object userState) {
            if ((this.SendMsgOperationCompleted == null)) {
                this.SendMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsgOperationCompleted);
            }
            this.InvokeAsync("SendMsg", new object[] {
                        tele,
                        msg}, this.SendMsgOperationCompleted, userState);
        }
        
        private void OnSendMsgOperationCompleted(object arg) {
            if ((this.SendMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsgCompleted(this, new SendMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.125:8002/SendMsg_315", RequestNamespace="http://192.168.1.125:8002/", ResponseNamespace="http://192.168.1.125:8002/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMsg_315(string tele, string msg) {
            object[] results = this.Invoke("SendMsg_315", new object[] {
                        tele,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMsg_315Async(string tele, string msg) {
            this.SendMsg_315Async(tele, msg, null);
        }
        
        /// <remarks/>
        public void SendMsg_315Async(string tele, string msg, object userState) {
            if ((this.SendMsg_315OperationCompleted == null)) {
                this.SendMsg_315OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsg_315OperationCompleted);
            }
            this.InvokeAsync("SendMsg_315", new object[] {
                        tele,
                        msg}, this.SendMsg_315OperationCompleted, userState);
        }
        
        private void OnSendMsg_315OperationCompleted(object arg) {
            if ((this.SendMsg_315Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsg_315Completed(this, new SendMsg_315CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.125:8002/SendMsg_Budiot_XFGWNormal", RequestNamespace="http://192.168.1.125:8002/", ResponseNamespace="http://192.168.1.125:8002/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMsg_Budiot_XFGWNormal(string tele, string msg) {
            object[] results = this.Invoke("SendMsg_Budiot_XFGWNormal", new object[] {
                        tele,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_XFGWNormalAsync(string tele, string msg) {
            this.SendMsg_Budiot_XFGWNormalAsync(tele, msg, null);
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_XFGWNormalAsync(string tele, string msg, object userState) {
            if ((this.SendMsg_Budiot_XFGWNormalOperationCompleted == null)) {
                this.SendMsg_Budiot_XFGWNormalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsg_Budiot_XFGWNormalOperationCompleted);
            }
            this.InvokeAsync("SendMsg_Budiot_XFGWNormal", new object[] {
                        tele,
                        msg}, this.SendMsg_Budiot_XFGWNormalOperationCompleted, userState);
        }
        
        private void OnSendMsg_Budiot_XFGWNormalOperationCompleted(object arg) {
            if ((this.SendMsg_Budiot_XFGWNormalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsg_Budiot_XFGWNormalCompleted(this, new SendMsg_Budiot_XFGWNormalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.125:8002/SendMsg_Budiot_ET315WNormal", RequestNamespace="http://192.168.1.125:8002/", ResponseNamespace="http://192.168.1.125:8002/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMsg_Budiot_ET315WNormal(string tele, string msg) {
            object[] results = this.Invoke("SendMsg_Budiot_ET315WNormal", new object[] {
                        tele,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_ET315WNormalAsync(string tele, string msg) {
            this.SendMsg_Budiot_ET315WNormalAsync(tele, msg, null);
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_ET315WNormalAsync(string tele, string msg, object userState) {
            if ((this.SendMsg_Budiot_ET315WNormalOperationCompleted == null)) {
                this.SendMsg_Budiot_ET315WNormalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsg_Budiot_ET315WNormalOperationCompleted);
            }
            this.InvokeAsync("SendMsg_Budiot_ET315WNormal", new object[] {
                        tele,
                        msg}, this.SendMsg_Budiot_ET315WNormalOperationCompleted, userState);
        }
        
        private void OnSendMsg_Budiot_ET315WNormalOperationCompleted(object arg) {
            if ((this.SendMsg_Budiot_ET315WNormalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsg_Budiot_ET315WNormalCompleted(this, new SendMsg_Budiot_ET315WNormalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.125:8002/SendMsg_Budiot_XFBNormal", RequestNamespace="http://192.168.1.125:8002/", ResponseNamespace="http://192.168.1.125:8002/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMsg_Budiot_XFBNormal(string tele, string msg) {
            object[] results = this.Invoke("SendMsg_Budiot_XFBNormal", new object[] {
                        tele,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_XFBNormalAsync(string tele, string msg) {
            this.SendMsg_Budiot_XFBNormalAsync(tele, msg, null);
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_XFBNormalAsync(string tele, string msg, object userState) {
            if ((this.SendMsg_Budiot_XFBNormalOperationCompleted == null)) {
                this.SendMsg_Budiot_XFBNormalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsg_Budiot_XFBNormalOperationCompleted);
            }
            this.InvokeAsync("SendMsg_Budiot_XFBNormal", new object[] {
                        tele,
                        msg}, this.SendMsg_Budiot_XFBNormalOperationCompleted, userState);
        }
        
        private void OnSendMsg_Budiot_XFBNormalOperationCompleted(object arg) {
            if ((this.SendMsg_Budiot_XFBNormalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsg_Budiot_XFBNormalCompleted(this, new SendMsg_Budiot_XFBNormalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.125:8002/SendMsg_Budiot_CXTSNormal", RequestNamespace="http://192.168.1.125:8002/", ResponseNamespace="http://192.168.1.125:8002/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMsg_Budiot_CXTSNormal(string tele, string msg) {
            object[] results = this.Invoke("SendMsg_Budiot_CXTSNormal", new object[] {
                        tele,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_CXTSNormalAsync(string tele, string msg) {
            this.SendMsg_Budiot_CXTSNormalAsync(tele, msg, null);
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_CXTSNormalAsync(string tele, string msg, object userState) {
            if ((this.SendMsg_Budiot_CXTSNormalOperationCompleted == null)) {
                this.SendMsg_Budiot_CXTSNormalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsg_Budiot_CXTSNormalOperationCompleted);
            }
            this.InvokeAsync("SendMsg_Budiot_CXTSNormal", new object[] {
                        tele,
                        msg}, this.SendMsg_Budiot_CXTSNormalOperationCompleted, userState);
        }
        
        private void OnSendMsg_Budiot_CXTSNormalOperationCompleted(object arg) {
            if ((this.SendMsg_Budiot_CXTSNormalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsg_Budiot_CXTSNormalCompleted(this, new SendMsg_Budiot_CXTSNormalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.125:8002/SendMsg_Budiot_MQYNormal", RequestNamespace="http://192.168.1.125:8002/", ResponseNamespace="http://192.168.1.125:8002/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMsg_Budiot_MQYNormal(string tele, string msg) {
            object[] results = this.Invoke("SendMsg_Budiot_MQYNormal", new object[] {
                        tele,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_MQYNormalAsync(string tele, string msg) {
            this.SendMsg_Budiot_MQYNormalAsync(tele, msg, null);
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_MQYNormalAsync(string tele, string msg, object userState) {
            if ((this.SendMsg_Budiot_MQYNormalOperationCompleted == null)) {
                this.SendMsg_Budiot_MQYNormalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsg_Budiot_MQYNormalOperationCompleted);
            }
            this.InvokeAsync("SendMsg_Budiot_MQYNormal", new object[] {
                        tele,
                        msg}, this.SendMsg_Budiot_MQYNormalOperationCompleted, userState);
        }
        
        private void OnSendMsg_Budiot_MQYNormalOperationCompleted(object arg) {
            if ((this.SendMsg_Budiot_MQYNormalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsg_Budiot_MQYNormalCompleted(this, new SendMsg_Budiot_MQYNormalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.125:8002/SendMsg_xianglehui", RequestNamespace="http://192.168.1.125:8002/", ResponseNamespace="http://192.168.1.125:8002/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMsg_xianglehui(string tele, string msg) {
            object[] results = this.Invoke("SendMsg_xianglehui", new object[] {
                        tele,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMsg_xianglehuiAsync(string tele, string msg) {
            this.SendMsg_xianglehuiAsync(tele, msg, null);
        }
        
        /// <remarks/>
        public void SendMsg_xianglehuiAsync(string tele, string msg, object userState) {
            if ((this.SendMsg_xianglehuiOperationCompleted == null)) {
                this.SendMsg_xianglehuiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsg_xianglehuiOperationCompleted);
            }
            this.InvokeAsync("SendMsg_xianglehui", new object[] {
                        tele,
                        msg}, this.SendMsg_xianglehuiOperationCompleted, userState);
        }
        
        private void OnSendMsg_xianglehuiOperationCompleted(object arg) {
            if ((this.SendMsg_xianglehuiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsg_xianglehuiCompleted(this, new SendMsg_xianglehuiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.125:8002/SendMsg_Budiot_Wisdom315", RequestNamespace="http://192.168.1.125:8002/", ResponseNamespace="http://192.168.1.125:8002/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMsg_Budiot_Wisdom315(string tele, string msg) {
            object[] results = this.Invoke("SendMsg_Budiot_Wisdom315", new object[] {
                        tele,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_Wisdom315Async(string tele, string msg) {
            this.SendMsg_Budiot_Wisdom315Async(tele, msg, null);
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_Wisdom315Async(string tele, string msg, object userState) {
            if ((this.SendMsg_Budiot_Wisdom315OperationCompleted == null)) {
                this.SendMsg_Budiot_Wisdom315OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsg_Budiot_Wisdom315OperationCompleted);
            }
            this.InvokeAsync("SendMsg_Budiot_Wisdom315", new object[] {
                        tele,
                        msg}, this.SendMsg_Budiot_Wisdom315OperationCompleted, userState);
        }
        
        private void OnSendMsg_Budiot_Wisdom315OperationCompleted(object arg) {
            if ((this.SendMsg_Budiot_Wisdom315Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsg_Budiot_Wisdom315Completed(this, new SendMsg_Budiot_Wisdom315CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.125:8002/SendMsg_Budiot_Wisdom315Normal", RequestNamespace="http://192.168.1.125:8002/", ResponseNamespace="http://192.168.1.125:8002/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMsg_Budiot_Wisdom315Normal(string tele, string msg) {
            object[] results = this.Invoke("SendMsg_Budiot_Wisdom315Normal", new object[] {
                        tele,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_Wisdom315NormalAsync(string tele, string msg) {
            this.SendMsg_Budiot_Wisdom315NormalAsync(tele, msg, null);
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_Wisdom315NormalAsync(string tele, string msg, object userState) {
            if ((this.SendMsg_Budiot_Wisdom315NormalOperationCompleted == null)) {
                this.SendMsg_Budiot_Wisdom315NormalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsg_Budiot_Wisdom315NormalOperationCompleted);
            }
            this.InvokeAsync("SendMsg_Budiot_Wisdom315Normal", new object[] {
                        tele,
                        msg}, this.SendMsg_Budiot_Wisdom315NormalOperationCompleted, userState);
        }
        
        private void OnSendMsg_Budiot_Wisdom315NormalOperationCompleted(object arg) {
            if ((this.SendMsg_Budiot_Wisdom315NormalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsg_Budiot_Wisdom315NormalCompleted(this, new SendMsg_Budiot_Wisdom315NormalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.125:8002/SendMsg_Budiot_Wisdom315NormalAsmx", RequestNamespace="http://192.168.1.125:8002/", ResponseNamespace="http://192.168.1.125:8002/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMsg_Budiot_Wisdom315NormalAsmx(string tele, string msg) {
            object[] results = this.Invoke("SendMsg_Budiot_Wisdom315NormalAsmx", new object[] {
                        tele,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_Wisdom315NormalAsmxAsync(string tele, string msg) {
            this.SendMsg_Budiot_Wisdom315NormalAsmxAsync(tele, msg, null);
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_Wisdom315NormalAsmxAsync(string tele, string msg, object userState) {
            if ((this.SendMsg_Budiot_Wisdom315NormalAsmxOperationCompleted == null)) {
                this.SendMsg_Budiot_Wisdom315NormalAsmxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsg_Budiot_Wisdom315NormalAsmxOperationCompleted);
            }
            this.InvokeAsync("SendMsg_Budiot_Wisdom315NormalAsmx", new object[] {
                        tele,
                        msg}, this.SendMsg_Budiot_Wisdom315NormalAsmxOperationCompleted, userState);
        }
        
        private void OnSendMsg_Budiot_Wisdom315NormalAsmxOperationCompleted(object arg) {
            if ((this.SendMsg_Budiot_Wisdom315NormalAsmxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsg_Budiot_Wisdom315NormalAsmxCompleted(this, new SendMsg_Budiot_Wisdom315NormalAsmxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.125:8002/SendMsg_Budiot_XLH", RequestNamespace="http://192.168.1.125:8002/", ResponseNamespace="http://192.168.1.125:8002/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMsg_Budiot_XLH(string tele, string msg) {
            object[] results = this.Invoke("SendMsg_Budiot_XLH", new object[] {
                        tele,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_XLHAsync(string tele, string msg) {
            this.SendMsg_Budiot_XLHAsync(tele, msg, null);
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_XLHAsync(string tele, string msg, object userState) {
            if ((this.SendMsg_Budiot_XLHOperationCompleted == null)) {
                this.SendMsg_Budiot_XLHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsg_Budiot_XLHOperationCompleted);
            }
            this.InvokeAsync("SendMsg_Budiot_XLH", new object[] {
                        tele,
                        msg}, this.SendMsg_Budiot_XLHOperationCompleted, userState);
        }
        
        private void OnSendMsg_Budiot_XLHOperationCompleted(object arg) {
            if ((this.SendMsg_Budiot_XLHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsg_Budiot_XLHCompleted(this, new SendMsg_Budiot_XLHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.125:8002/SendMsg_Budiot_XLHNormal", RequestNamespace="http://192.168.1.125:8002/", ResponseNamespace="http://192.168.1.125:8002/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMsg_Budiot_XLHNormal(string tele, string msg) {
            object[] results = this.Invoke("SendMsg_Budiot_XLHNormal", new object[] {
                        tele,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_XLHNormalAsync(string tele, string msg) {
            this.SendMsg_Budiot_XLHNormalAsync(tele, msg, null);
        }
        
        /// <remarks/>
        public void SendMsg_Budiot_XLHNormalAsync(string tele, string msg, object userState) {
            if ((this.SendMsg_Budiot_XLHNormalOperationCompleted == null)) {
                this.SendMsg_Budiot_XLHNormalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsg_Budiot_XLHNormalOperationCompleted);
            }
            this.InvokeAsync("SendMsg_Budiot_XLHNormal", new object[] {
                        tele,
                        msg}, this.SendMsg_Budiot_XLHNormalOperationCompleted, userState);
        }
        
        private void OnSendMsg_Budiot_XLHNormalOperationCompleted(object arg) {
            if ((this.SendMsg_Budiot_XLHNormalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsg_Budiot_XLHNormalCompleted(this, new SendMsg_Budiot_XLHNormalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendMsgCompletedEventHandler(object sender, SendMsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendMsg_315CompletedEventHandler(object sender, SendMsg_315CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMsg_315CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMsg_315CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendMsg_Budiot_XFGWNormalCompletedEventHandler(object sender, SendMsg_Budiot_XFGWNormalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMsg_Budiot_XFGWNormalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMsg_Budiot_XFGWNormalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendMsg_Budiot_ET315WNormalCompletedEventHandler(object sender, SendMsg_Budiot_ET315WNormalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMsg_Budiot_ET315WNormalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMsg_Budiot_ET315WNormalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendMsg_Budiot_XFBNormalCompletedEventHandler(object sender, SendMsg_Budiot_XFBNormalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMsg_Budiot_XFBNormalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMsg_Budiot_XFBNormalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendMsg_Budiot_CXTSNormalCompletedEventHandler(object sender, SendMsg_Budiot_CXTSNormalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMsg_Budiot_CXTSNormalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMsg_Budiot_CXTSNormalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendMsg_Budiot_MQYNormalCompletedEventHandler(object sender, SendMsg_Budiot_MQYNormalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMsg_Budiot_MQYNormalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMsg_Budiot_MQYNormalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendMsg_xianglehuiCompletedEventHandler(object sender, SendMsg_xianglehuiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMsg_xianglehuiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMsg_xianglehuiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendMsg_Budiot_Wisdom315CompletedEventHandler(object sender, SendMsg_Budiot_Wisdom315CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMsg_Budiot_Wisdom315CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMsg_Budiot_Wisdom315CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendMsg_Budiot_Wisdom315NormalCompletedEventHandler(object sender, SendMsg_Budiot_Wisdom315NormalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMsg_Budiot_Wisdom315NormalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMsg_Budiot_Wisdom315NormalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendMsg_Budiot_Wisdom315NormalAsmxCompletedEventHandler(object sender, SendMsg_Budiot_Wisdom315NormalAsmxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMsg_Budiot_Wisdom315NormalAsmxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMsg_Budiot_Wisdom315NormalAsmxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendMsg_Budiot_XLHCompletedEventHandler(object sender, SendMsg_Budiot_XLHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMsg_Budiot_XLHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMsg_Budiot_XLHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendMsg_Budiot_XLHNormalCompletedEventHandler(object sender, SendMsg_Budiot_XLHNormalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMsg_Budiot_XLHNormalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMsg_Budiot_XLHNormalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591